version: '3.8'

services:
  nest-app:
    image: ghcr.io/ifpebj-ti/back-pe-estudantes:1.1.0
    container_name: nest-backend
    ports:
      - "3001:3000" # expõe porta 3001 na VM
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      NODE_ENV: "${NODE_ENV}"
    networks:
      - app-net
      - proxy-net
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-net

  next-app:
    image: ghcr.io/ifpebj-ti/front-pe-estudantes:0.3.1
    container_name: next-frontend
    ports:
      - "8080:3000" # expõe porta 8080 na VM
    networks:
      - app-net
      - proxy-net
    depends_on:
      - nest-app

networks:
  app-net:
    driver: bridge

  proxy-net:
    external: true

volumes:
  pgdata:
