on:
  push:
    branches: 
      - "main"
    paths:
      - "front/**"
  pull_request:
    branches: 
      - "main"
    paths:
      - "front/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: front-pe-estudantes
      REGISTRY: ghcr.io
      TAG: ${{ github.sha }}

    steps:
    - uses: actions/checkout@v4

    # - name: Set up Node.js
    #   uses: actions/setup-node@v4
    #   with:
    #     node-version: 20

    # - name: Install dependencies
    #   working-directory: ./front
    #   run: npm ci

    # - name: Lint
    #   working-directory: ./front
    #   run: npm run lint

    # - name: Build frontend
    #   working-directory: ./front
    #   run: npm run build

    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Docker image
      run: |
        docker build ./front --file front/Dockerfile --tag $REGISTRY/${{ github.repository_owner }}/$IMAGE_NAME:$TAG

    - name: Push Docker image to GitHub Packages
      run: |
        docker push $REGISTRY/${{ github.repository_owner }}/$IMAGE_NAME:$TAG

    - name: Scan image for vulnerabilities with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ghcr.io/ifpebj-ti/front-pe-estudantes:${{ env.TAG }}
        format: table
        exit-code: 0
        severity: CRITICAL,HIGH
